Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" # Ubuntu 18.04

  config.vm.network "private_network", ip: "192.168.33.40"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    curl -L https://chef.io/chef/install.sh | sudo bash
  SHELL

  # Chef Provision
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "./cookbooks"
    chef.add_recipe "nginx"
    chef.arguments = "--chef-license accept"
    chef.install = false
  end
end

# Finally, go to the browser and invoke http://192.168.33.40, you will see the NGINX default page